import type React from "react";
import { BackToTop } from "./components/back-to-top";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  other: {
    "google-adsense-account": "ca-pub-2694217258702912",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#141414] text-white scrollbar-hide">
        {/* Script do AdSense - Adicionar após aprovação */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2694217258702912"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        <BackToTop />

        <Script
          id="tawk-chat"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
            (function(){
              var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
              s1.async=true;
              s1.src='https://embed.tawk.to/686122730fa35a190e03dfde/1iutmt4qe';
              s1.charset='UTF-8';
              s1.setAttribute('crossorigin','*');
              s0.parentNode.insertBefore(s1,s0);
            })();
          `,
          }}
        />

        {children}
      </body>
    </html>
  );
}
