import type React from "react";
import { BackToTop } from "./components/back-to-top";
import Script from "next/script";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  other: {
    "google-adsense-account": "ca-pub-2694217258702912",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#141414] text-white scrollbar-hide">
        {/* Script do AdSense - Adicionar após aprovação */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2694217258702912"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        <BackToTop />
        {children}
      </body>
    </html>
  );
}
