import { BackToTop } from "./components/back-to-top";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#141414] text-white scrollbar-hide">
        <BackToTop />
        {children}
      </body>
    </html>
  );
}
